### ISSUE TITLE
Can't use the extension

### ISSUE THREAD

**Issue by SkourtsidisGiorgos** [data-diving/superset-xlsx#1]
I could not understand the installation steps. Can you please help me / describe the process? 
Thank you in advance.

**Comment by aleksandrgordienko** [comment]
Hey,
Firstly, you have to clone repo to your local machine with this command:
`git clone`
Secondly, build Docker image from it:
`docker build --tag data-diving/superset-xlsx .`
And then, you can follow [these instructions](https://medium.com/geekculture/run-apache-superset-locally-in-10-minutes-30bc70ed808c) replacing standard `apache/superset` in docker run command with `data-diving/superset-xlsx`
